config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :wishes do
    get :complete
  end
  resources :dones, only: [:index, :show, :destroy]
  resources :small_steps, only: [:update]
  root "wishes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/small_step.rb
class SmallStep < ApplicationRecord
  belongs_to :wish, dependent: :destroy

  def switch_done
    if self.done == false
      self.done = true
      self.save
    else
      self.done = false
      self.save
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wishes
end

app/models/wish.rb
class Wish < ApplicationRecord
  has_many :small_steps
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/dones_controller.rb
class DonesController < ApplicationController
  def index
    @wishes = Wish.where(user_id: current_user.id, completed: true)
  end

  def show
    @wish = Wish.find(params[:id])
  end

  def destroy
    wish = Wish.find(params[:id])
    wish.destroy
    redirect_to :action => "index"
  end
end

app/controllers/small_steps_controller.rb
class SmallStepsController < ApplicationController
  def update
    small_step = SmallStep.find(params[:id])
    small_step.switch_done
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

  
  def index
    @wishes = Wish.where(user_id: current_user.id, completed: false)
  end

  def new
    @wish = Wish.new
  end

  def create
    wish = Wish.create(wish_params)
    small_step_params.each_value{|value|
      if value != ""
        SmallStep.create(text: value, wish_id: wish.id)
      end
    }
    redirect_to :action => "index"
  end

  def show
    @wish = Wish.find(params[:id])
  end

  def update
    wish = Wish.find(params[:id])
    
    if wish.user == current_user
      wish.update(wish_params)

      small_steps_ids = []
      #small_step_update_paramsのメモ{"text1"=>"繰り返し１", "text2"=>"繰り返し２", "text3"=>"繰り返し３", "small_step_id1"=>"56", "small_step_id2"=>"57", "small_step_id3"=>"58"} 
      
      num=1
      3.times do
        key = "small_step_id"
        key = key + num.to_s
        small_steps_ids << small_step_update_params[key.to_sym]
        num += 1
      end

      text_num=1

      small_steps_ids.each_with_index do |id,i|
        key = "text" + text_num.to_s
        if SmallStep.exists?(small_steps_ids[i])
          SmallStep.find(small_steps_ids[i]).update(text: small_step_update_params[key.to_sym]) 
        else
            SmallStep.create(text: small_step_update_params[key.to_sym], wish_id: wish.id)
        end
        text_num += 1
      end
      redirect_to wish_path(wish)

    else
      redirect_to :action => "index"
    end
  end

  def destroy
    wish = Wish.find(params[:id])

    if wish.user == current_user
      wish.destroy
    end
    
    redirect_to :action => "index"
  end

  def complete
    wish=Wish.find(params[:wish_id])
    wish.completed = true
    wish.save
  end

  private
  def wish_params
    wish_params = params.require(:wish).permit(:title, :memo, :deadline).merge(user_id: current_user.id)
  end

  def small_step_params
    small_step_params = params.require(:wish).permit(small_step: [:text1,:text2, :text3])
    # paramsからsmall_stepの情報を取得
    small_step_params = small_step_params.require(:small_step).permit(:text1, :text2, :text3)
  end

  def small_step_update_params
    small_step_params = params.require(:wish).permit(small_step: [:text1,:text2, :text3, :small_step_id1, :small_step_id2, :small_step_id3])
    # paramsからsmall_stepの情報を取得
    small_step_params = small_step_params.require(:small_step).permit(:text1, :text2, :text3,:small_step_id1, :small_step_id2, :small_step_id3)
  end
  #HACK:あとで繰り返し処理にする
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dones_helper.rb
module DonesHelper
end

app/helpers/small_steps_helper.rb
module SmallStepsHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/dones/donelist.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@500&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/d18240d4e8.js" crossorigin="anonymous"></script>
  <title>一覧ページ</title>
</head>
<body>
  <header class="header">
    <div class="header-contents wrapper">
      <div class="header-logo">
        <%= image_tag 'logo.png', class: "header-logo__image"%>
      </div>
      <ul class="header-menu">
        <li class="header-menu__item"><a class="header-menu__link">mami</a></li>
        <li class="header-menu__item"><a class="header-menu__link">達成済み</a></li>
      </ul>
    </div>
  </header>
  <main class="main">
    
    <div class="main-btn-area">
      <a class="new-post-btn main-btn">wishリストを追加する</a>
    </div>

    <div class="main-area">
    <div class="whishes-bord wrapper">
      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav-item"><a href="#" class="nav-item__link">編集</a></li>
          <li class="nav-item"><a href="#" class="nav-item__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>

      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav__item"><a href="#" class="nav__link">編集</a></li>
          <li class="nav__item"><a href="#" class="nav__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>

      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav-item"><a href="#" class="nav-item__link">編集</a></li>
          <li class="nav-item"><a href="#" class="nav-item__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>

      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav-item"><a href="#" class="nav-item__link">編集</a></li>
          <li class="nav-item"><a href="#" class="nav-item__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>
      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav-item"><a href="#" class="nav-item__link">編集</a></li>
          <li class="nav-item"><a href="#" class="nav-item__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>
      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav-item"><a href="#" class="nav-item__link">編集</a></li>
          <li class="nav-item"><a href="#" class="nav-item__link">削除</a></li>
          </ul>
        </div>
        <div class="wish-panel__item">
        〇〇さんの画像を作成する
        </div>
        <div class="wish-panel__deadline">
        2021/1/31
        </div>
      </div>
    </div>
    </div>
  </main>
</body>
</html>

app/views/dones/index.html.erb
<div class="main-btn-area">
      <a class="done-page-title">達成済み</a>
    </div>

    <div class="main-area dones">
      <div class="whishes-bord wrapper">
        <% @wishes.each do |wish| %>
          <div class="wish-panel">
            <div class="wish-panel__icon">
              <i class="fas fa-ellipsis-h"></i>
              <ul class="nav">
              <li class="nav__item"><%= link_to "詳細", done_path(wish), class: "nav__link" %></li>
              <li class="nav__item"><%= link_to "削除", done_path(wish), method: :delete, class:"nav__link" %></li>
              </ul>
            </div>
            <div class="wish-panel__item">
            <%= wish.title%>
            </div>
            <div class="wish-panel__deadline">
            <%= wish.deadline%>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/dones/show.html.erb
<div class="main-area dones">
  <div class="contents-box">
    <div class="contents-box__head done-head">
      <div>
        <%= link_to "一覧に戻る", dones_path, class:"medium-btn-link " %>
      </div>
      <div class="contents-title done-show-title">詳細</div>
      <div class="blank-box"></div>
    </div>

    <ul class="contents-box-list">
      <li class="contents-box-list__item">
        <div class="item-title">達成したいこと</div>
        <div class="item-firld display"><%=@wish.title%></div>
      </li>
      <li class="contents-box-list__item">
        <div class="item-title">期限</div>
        <div class="item-firld display"><%=@wish.deadline%></div>
      </li>
      <li class="contents-box-list__item memo-height">
        <div class="list-items">
          <div class="item-title">
          メモ
          </div>
          <div class="item-firld display">
          <%= @wish.memo %>
          </div>
        </div>
      </li>
      <% number = ["①","②","③"]%>
      <% @wish.small_steps.zip(number) do |small_step,num|%>
      <li class="contents-box-list__item">
        <div class="small-step-items">
          <div class="small-step-items__contents">
            <div class="item-title">
            スモールステップ<%= num %>
            </div>
            <div class="item-firld display">
            <%= small_step.text %>
            </div>
          </div>
          <div class="done-display">
          達成済み
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WishlistManager</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@500&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/d18240d4e8.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="header">
        <div class="header-contents wrapper">
          <div class="header-logo">
            <a href="/">
            <%= image_tag 'logo.png', class: "header-logo__image"%>
            </a>
          </div>
          <ul class="header-menu">
          <% if user_signed_in? %>
            <li class="header-menu__item user_name"><a class="header-menu__link"><%= current_user.nickname %></a>
              <ul class="nav user-nav">
              <li class="nav__item"><%= link_to "ユーザー編集", edit_user_registration_path ,class: "nav__link" %>
              <li class="nav__item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__link" %>
              </ul>
            </li>
            <li class="header-menu__item"><%= link_to "達成済み", dones_path, class:"header-menu__link"%></li>
          <% end %>
          </ul>
        </div>
      </header>

      <main class="main">

        <%= yield %>
      </main>
  </body>
</html>

app/views/wishes/complete.html.erb
<div class="main-area">
  <div class="done-comment-panel">
    <p class="done-comment-panel__text">
      おめでとうございます！<br>
      また一つwishが叶いましたね。<br>
      あなたの人生がより実りあるものになりますように。
    </p>
  </div>
    <%= link_to "トップページへ戻る",root_path, class: "link-top-btn main-btn"%>
</div>

app/views/wishes/index.html.erb
<div class="main-btn-area">
  <%= link_to "wishリストを追加する", new_wish_path, class: "new-post-btn main-btn"%>
</div>

<div class="main-area">
  <div class="whishes-bord wrapper">
    <% @wishes.each do |wish|%>
      <div class="wish-panel">
        <div class="wish-panel__icon">
          <i class="fas fa-ellipsis-h"></i>
          <ul class="nav">
          <li class="nav__item"><%= link_to "詳細", wish_path(wish) ,class: "nav__link" %>
          <li class="nav__item"><%= link_to "削除", wish_path(wish), method: :delete, class: "nav__link" %>
          </ul>
        </div>
        <div class="wish-panel__item">
          <%= wish.title %>
        </div>
        <div class="wish-panel__deadline">
          <%= wish.deadline %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wishes/new.html.erb
<div class="main-area">
  <div class="contents-box">
    <div class="contents-box__head">
      <a href="/" class="medium-btn-link cancel">キャンセル</a>
      <div class="contents-title">新規wish</div>
      <a href="#" class="medium-btn-link" id="new_post">登録</a>
    </div>
    <div class ="contents-box-list">
    <%= form_for(@wish) do |f| %>
      <div class="contents-box-list__item flex">
        <%= f.label :title, "達成したいこと", class: "item-title" %>
        <%= f.text_field :title, class: "item-field", placeholder: "例)猫と暮らしたい" %>
      </div>
      <div class="contents-box-list__item flex">
        <%= f.label :deadline, "期限", class: "item-title" %>
        <%= f.date_select :deadline, class: "item-field" %>
      </div>
      <div class="contents-box-list__item">
        <%= f.label :memo, "メモ", class: "item-title memo-title" %>
        <%= f.text_area :memo, class: "item-field memo-height", placeholder: "500字以内で書いください" %>
      </div>
      <div class="contents-box-list__item">
      <%= f.fields_for :small_step do |i|%>
        <%= i.label :text1, "スモールステップ①", class: "item-title" %>
        <%= i.text_field :text1, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
      </div>
      <div class="contents-box-list__item">
        <%= i.label :text2, "スモールステップ②", class: "item-title"%>
        <%= i.text_field :text2, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
      </div>
      <div class="contents-box-list__item">
        <%= i.label :text3, "スモールステッ③", class: "item-title"%>
        <%= i.text_field :text3, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/wishes/show.html.erb
<div class="main-btn-area">
  <%= link_to "達成", wish_complete_path(@wish), class: "main-btn complete " %>
</div>
<div class="main-area">
  <div class="contents-box">
    <div class="contents-box__head">
      <a href="/" class="medium-btn-link cancel">キャンセル</a>
      <div class="contents-title">詳細</div>
      <a href="#" class="medium-btn-link" id="edit_post">登録</a>
    </div>

    <div class ="contents-box-list">
    <%= form_for(@wish, html: {name: 'edit_wish'}) do |f| %>
      <div class="contents-box-list__item flex">
        <%= f.label :title, "達成したいこと", class: "item-title" %>
        <%= f.text_field :title, class: "item-field", value: @wish.title, placeholder: "例)猫と暮らしたい" %>
      </div>
      <div class="contents-box-list__item flex">
        <%= f.label :deadline, "期限", class: "item-title" %>
        <%= f.date_field :deadline, value: @wish.deadline, class: "item-field" %>
      </div>
      <div class="contents-box-list__item">
        <%= f.label :memo, "メモ", class: "item-title memo-title" %>
        <%= f.text_area :memo, value: @wish.memo, class: "item-field memo-height", placeholder: "500字以内で書いください" %>
      </div>

      <%= f.fields_for :small_step do |i|%>
      <div class="contents-box-list__item">
        <% if @wish.small_steps[0] %>
          <div class="small-step-items">
            <div class="small-step-items__contents">
              <%= i.label :text1, "スモールステップ①", class: "item-title" %>
              <%= i.text_field :text1, class: "item-field", value: @wish.small_steps[0].text,placeholder: "例)ペット可の物件を探す" %>
              <%=i.hidden_field :small_step_id1, value:@wish.small_steps[0].id%>
            </div>
              <% if @wish.small_steps[0].done == true %>
            <%= link_to "達成", small_step_path( @wish.small_steps[0].id),method: :patch, class: "small-btn small-btn__done"%>
            <% else %>
            <%= link_to "達成", small_step_path( @wish.small_steps[0].id),method: :patch, class: "small-btn"%>
            <% end %>
          </div>
        <% else %>
          <div class="small-step-items">
            <div class="small-step-items__contents">
              <%= i.label :text1, "スモールステップ①", class: "item-title" %>
              <%= i.text_field :text1, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
            </div>
            <a href="#" class="small-btn">達成</a>
          </div>
        <% end %>
      </div>

      <div class="contents-box-list__item">
        <% if @wish.small_steps[1] %>
          <div class="small-step-items">
            <div class="small-step-items__contents">
              <%= i.label :text2, "スモールステップ②", class: "item-title" %>
              <%= i.text_field :text2, class: "item-field", value: @wish.small_steps[1].text,placeholder: "例)ペット可の物件を探す" %>
              <%=i.hidden_field :small_step_id2, value:@wish.small_steps[1].id%>
            </div>
            <% if @wish.small_steps[1].done == true %>
            <%= link_to "達成", small_step_path( @wish.small_steps[1].id),method: :patch, class: "small-btn small-btn__done"%>
            <% else %>
            <%= link_to "達成", small_step_path( @wish.small_steps[1].id),method: :patch, class: "small-btn"%>
            <% end %>
          </div>
        <% else %>
          <div class="small-step-items">
            <div class="small-step-items__contents">
              <%= i.label :text2, "スモールステップ②", class: "item-title" %>
              <%= i.text_field :text2, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
            </div>
            <a href="#" class="small-btn">達成</a>
          </div>
        <% end %>
      </div>

      <div class="contents-box-list__item">
        <% if @wish.small_steps[2] %>
          <div class="small-step-items">
            <div class="small-step-items__contents">
              <%= i.label :text3, "スモールステップ③", class: "item-title" %>
              <%= i.text_field :text3, class: "item-field", value: @wish.small_steps[2].text,placeholder: "例)ペット可の物件を探す" %>
              <%=i.hidden_field :small_step_id3, value:@wish.small_steps[2].id%>
            </div>
            <% if @wish.small_steps[1].done == true %>
            <%= link_to "達成", small_step_path( @wish.small_steps[2].id),method: :patch, class: "small-btn small-btn__done"%>
            <% else %>
            <%= link_to "達成", small_step_path( @wish.small_steps[2].id),method: :patch, class: "small-btn"%>
            <% end %>
          </div>
        <% else %>
        <div class="small-step-items">
          <div class="small-step-items__contents">
            <%= i.label :text3, "スモールステップ③", class: "item-title" %>
            <%= i.text_field :text3, class: "item-field", placeholder: "例)ペット可の物件を探す" %>
          </div>
          <a href="#" class="small-btn">達成</a>
        </div>
        <% end %>
      </div>

      <% end %>
    <% end %>
    </div>
  </div>
</div>